---
version: '2.1'
services:
  nginx:
    container_name: nginx
    image: bex/nginx:latest
    build: ./docker/nginx
    healthcheck:
      test: ["CMD-SHELL", "curl -k --silent --fail https://localhost"]
      interval: 60s
      timeout: 15s
      retries: 10
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - exchange
  exchange:
    container_name: exchange
    env_file: .env
    image: bex/exchange:latest
    build:
      context: .
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8000 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
    ports:
      - 8000:8000
    depends_on:
      - db
      - search
      - task_queue
    volumes:
      - $PWD:/code:rw  # needed for running tests and coverage
      - django_media:/app/data/media
  geoserver:
    container_name: geoserver
    build: ./docker/geoserver
    image: bex/geoserver:latest
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8080/geoserver/web/ || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
    ports:
      - '8080:8080'
    depends_on:
      - db
    volumes:
      - geoserver_data:/usr/local/tomcat/webapps/geoserver/data:rw
  db:
    container_name: db
    build: ./docker/postgis
    image: bex/postgis:latest
    mem_limit: 1024m
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
    environment:
      ALLOW_IP_RANGE: '0.0.0.0/0'
      POSTGRES_USER: 'root'
      DB_USER: 'exchange'
      DB_PASS: 'boundless'
    volumes:
      - db_data:/var/lib/postgresql/data
  task_queue:
    container_name: task_queue
    image: rabbitmq:3.6-management-alpine
    ports:
      - 5672:5672
      - 15672:15672  # rabbitmq management plugin
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
    volumes:
      - search_data:/var/lib/rabbitmq
  search:
    container_name: search
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      core:
        soft: -1
        hard: -1
      fsize:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
    volumes:
      - queue_data:/usr/share/elasticsearch/data/elasticsearch
volumes:  # volumes with no displayed path/relationship to the host
  django_media:
  geoserver_data:
  db_data:
  search_data:
  queue_data:
